config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) 

  devise_for :users

  root to: "hotels#index"
  resources :bookings 
  # resources:users
  # get '/index', to: 'users#index'
  # post 'user/login', to: 'users#login'
  # patch 'users', to: 'users#update'
  # put 'users', to: 'users#update'
  # delete 'users', to: 'users#destroy'
  resources :hotels 
  resources :rooms
  
  get '/available_hotels', to: 'customers#available_hotels'
  
  
  post '/forget_password', to: 'passwords#forget_password_email'
  post '/reset_password', to: 'passwords#reset_password'
  post '/verify_otp', to: 'passwords#verify_otp'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  belongs_to :hotel

  validates :check_in_date, :check_out_date, presence: true
  validate :unique_room_booking

  private
  
  def unique_room_booking 
    existing_booking = Booking.find_by(room: room_id, check_in_date: check_in_date, hotel_id: hotel_id ) 
    if existing_booking.present?
      errors.add(:base, "this room is already booked!!")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["check_in_date", "check_out_date", "created_at", "hotel_id", "id", "name", "room_id", "updated_at", "user_id"]
  end 
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_bookings, only: [:destroy, :update, :edit]
  
  def index
    @bookings = current_user.bookings
  end

  def new 
    @booking = current_user.bookings.new
  end

  def create
    @booking = current_user.bookings.new(booking_params)
  
    if @booking.save
   
     redirect_to root_path
    else
      render json: { error: @booking.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    @booking = current_user.bookings.find(params[:id])
  end

  def edit 
  end

  def update
    respond_to do |format|
      debugger
      if @booking.update(update_booking)
    
        format.html { redirect_to root_url, notice: "booking was successfully updated." }
        # format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @booking
      booking = @booking.destroy
      redirect_to booking_path
    end
  end

  private
  def booking_params
    params.require(:booking).permit(:name, :check_in_date, :check_out_date).merge(hotel_id: params[:booking][:hotel_id].to_i,room_id: params[:booking][:room_id].to_i)
  end

  def set_bookings
    @booking = current_user.bookings.find_by(id: params[:id])
  end

  def update_booking
    params.require(:booking).permit(:name, :check_in_date, :check_out_date)
  end

end

app/views/bookings/edit.html.erb
  <h1> Edit Bookings</h1>

  <%= form_with(model: @booking) do |form| %>
    <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name%>
    </div>
  
    <div>
      <%= form.label :check_in_date, style: "display: block" %>
      <%= form.date_field :check_in_date%>
    </div>
    
    <div>
      <%= form.label :check_out_date, style: "display: block" %>
      <%= form.date_field:check_out_date%>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <%end%>
      
  

app/views/bookings/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hotels</title>
</head>
	<body>
	<h1>Bookings</h1>
	<div class="container">
		<% current_user.bookings.each do |booking| %>
			<strong>name</strong>
			<%= booking.name%>
            <br>
			<strong>check_in_date</strong>
			<%= booking.check_in_date %>
            <br>
			<strong>check_out_date</strong>
			<%= booking.check_out_date %>
			<br>
			<li><%= link_to "Destroy", booking_path(booking), data: {
				turbo_method: :delete,
				turbo_confirm: "Are you sure?"
			  } %></li>
			<%= link_to "Edit booking", edit_booking_path(booking) %> 

		<%end%>
	</div>

	</body>
</html>

app/views/bookings/new.html.erb
<%= form_with(model: @booking) do |form| %>
    <% if @booking.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@booking.errors.count, "error") %> </h2>
  
        <ul>
          <% @booking.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
    <%= form.hidden_field :hotel_id, :value => params[:hotel_id] %>
    <%= form.hidden_field :room_id, :value => params[:room_id] %>
    </div>

    <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name%>
    </div>
  
    <div>
      <%= form.label :check_in_date, style: "display: block" %>
      <%= form.date_field :check_in_date%>
    </div>
    
    <div>
      <%= form.label :check_out_date, style: "display: block" %>
      <%= form.date_field:check_out_date%>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/bookings/show.html.erb
<%= render partial: 'booking', locals: {booking: @booking}  %>

<div>

  <%= link_to "Back to hotels", hotels_path %> 

  <%if current_user.type == 'customer'%>
    <%= link_to "Edit booking", edit_booking_path(@booking) %> 
    <%= button_to "Destroy this booking", @booking, method: :delete %>
  <%end%>
</div>  