config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) 

  devise_for :users

  root to: "hotels#index"
  resources :bookings 
  # resources:users
  # get '/index', to: 'users#index'
  # post 'user/login', to: 'users#login'
  # patch 'users', to: 'users#update'
  # put 'users', to: 'users#update'
  # delete 'users', to: 'users#destroy'
  resources :hotels 
  resources :rooms
  
  get '/available_hotels', to: 'customers#available_hotels'
  
  
  post '/forget_password', to: 'passwords#forget_password_email'
  post '/reset_password', to: 'passwords#reset_password'
  post '/verify_otp', to: 'passwords#verify_otp'
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :user
  has_many :rooms
  has_many :bookings
  has_many_attached :images
 

  enum :status, [:open, :close]
  validates :name, :location, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "location", "name", "status", "updated_at", "user_id"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["bookings", "images_attachments", "images_blobs", "rooms", "user"]
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController 
  before_action :set_params, only: [:update, :destroy, :edit]
  def index 
    @hotels = Hotel.all

    if params[:location]
      @hotels = hotels.where('location LIKE  ?', "%#{params[:location]}%")
    elsif params[:name]
      @hotels = hotels.where('name LIKE ?', "%#{ params[:name]}%")
    end 
  end

  def show
    if current_user.type == 'Owner'
      @hotels = current_user.hotels.find(params[:id]) 
    else
      @hotels = Hotel.find(params[:id])
    end
  end

  def new 
    @hotels = current_user.hotels.new
  end
  
  def create
    hotel = current_user.hotels.new(hotel_params)
     
    if hotel.save
      
      redirect_to root_path    
    else
      render json: { error: hotel.errors.full_messages }, status: :unprocessable_entity
    end
  end 

  def edit 
  end

  def update
    respond_to do |format|
      if @hotels.update(hotel_params)
        # debugger
        format.html { redirect_to root_url, notice: "hotel was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @hotels.destroy
      redirect_to root_path    
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :location, :status, images: [])
  end

  def set_params
    @hotels = @current_user.hotels.find(params[:id])
  end 
end 

app/views/hotels/_form.html.erb
<%= form_with(model: hotels) do |form| %>
    <% if hotels.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(hotels.errors.count, "error") %> prohibited this hotel from being saved:</h2>
  
        <ul>
          <% hotels.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.label :location, style: "display: block" %>
      <%= form.text_field :location %>
    </div>
  
    <div>
      <%= form.select :status, ['open','close' ] %>
    </div>
    
    <div>
      <%=form.label :images%>
      <%=form.file_field :images, multiple: true, direct_upload: 'false'%>
    </div>
   
    <div>
      <%= form.submit %>
    </div>
  
  <% end %>

app/views/hotels/_hotels.html.erb
<div id="<%= dom_id hotels %>">
  <p>
    <strong>Name:</strong>
    <%= hotels.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= hotels.location %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= hotels.status %>
  </p>

  <p>
    <% if hotels.images.attached? %>
      <% hotels.images.each do |image|%>
        <image src="<%=(url_for(image))%>">
      <% end %>
    <%end%>  
  </p>

  <p>
  <u>
  <h3>Available Rooms</h3>
  </u>
  <% hotels.rooms.each do |room|%>
      <strong>room_no.</strong>
      <%= room.room_no %>
      <strong>room_price.</strong>
      <%= room.room_price %>
    
      <%if current_user.type == 'Customer'%>
        <%= link_to "Book Room", new_booking_path(:room_id => room.id, :hotel_id => hotels.id)%>
      <%else%>
        <%= link_to "edit room", edit_room_path(:hotel_id => hotels.id)%>
      <%end%>
  <% end %>
  </p>
</div>

app/views/hotels/edit.html.erb
<h1>Edit hotel</h1>

<%= render "form", hotels: @hotels %>

<br>

<div>
  <%= link_to "Show this hotel", @hotels %> 
  <%= link_to "Back to hotel", hotel_path %>
</div>

app/views/hotels/index.html.erb
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>



<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hotels</title>
  <style>
    body {
      font-family: Tahoma, sans-serif;
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
      margin: 0;
      padding: 0;
    }
    h1 {
      color: #007BFF;
      text-align: center;
      padding-top: 20px;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      background-color: rgba(255, 255, 255, 0.9);
      border: 1px solid #ccc;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .hotel-card {
      display: flex;
      margin-bottom: 20px;
    }
    .hotel-details {
      flex: 1;
      padding: 20px;
    }
    .hotel-name {
      font-size: 24px;
      color: #333;
      margin-bottom: 10px;
    }
 
    .image {
      width: 200px;
      height: 300px;
      margin-right: 20px;
      border: 1px solid #ddd;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
    }
    .actions {
      margin-top: 10px;
    }
    .actions a {
      text-decoration: none;
      color: #007BFF;
      margin-right: 10px;
    }
  </style>
</head>

  <body>
    <h1>Hotels</h1>
    <div class="container">
      <% @hotels.each do |hotel| %>
        <div class="hotel-card">
          <div class="hotel-details">
            <div class="hotel-name"><%= hotel.name %></div>
            <div class="hotel-location"><%= hotel.location %></div>
            <div class="hotel-status"><%= hotel.status %></div>
            <div class="actions">
              <%= link_to 'Show', hotel %> 
            </div>
          </div>
        </div>
      <%end%>
    </div>

    <div>
      <%if current_user.type == 'Owner'%>
        <%= link_to "New hotel", new_hotel_path %>
      <%else%>
        <%= link_to "booking", {controller: "bookings", action: "index"} %>  
      <% end%>
    </div>

  </body>
</html>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render "form", hotels: @hotels%>

<br>

<div>
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/show.html.erb
<%= render partial: 'hotels', locals: {hotels: @hotels}  %>

<div>

  <%= link_to "Back to hotels", hotels_path %> 

  <%if current_user.type == 'Owner'%>
    <%= link_to "Edit this hotel", edit_hotel_path(@hotels) %> 
    <%= button_to "Destroy this hotel", @hotels, method: :delete %>
    <%= link_to "Add room to hotel",  new_room_path(:hotel_id => @hotels.id) %>
  
    <%end%>
</div> 